# https://bun.com/docs/guides/ecosystem/docker
FROM docker.io/oven/bun:1 AS base
WORKDIR /usr/src/app

# install dependencies into temp directory
# this will cache them and speed up future builds
#FROM base AS install
# 
# # install with --production (exclude devDependencies)
#RUN mkdir -p /temp/prod
#COPY package.json bun.lock /temp/prod/
#RUN cd /temp/prod && bun install --frozen-lockfile --production

# copy node_modules from temp directory
# then copy all (non-ignored) project files into the image
# FROM base AS prerelease
# COPY --from=install /temp/dev/node_modules node_modules
# COPY . .

# [optional] tests & build
# ENV NODE_ENV=production
# # RUN bun test
# RUN bun run build

# copy production dependencies and source code into final image
FROM base AS release
RUN apt-get update \
 && apt-get install -y --no-install-recommends libglib2.0-0 libnspr4 libnss3 libatk1.0-0 libatk-bridge2.0-0 libcups2 libxkbcommon0 libxcomposite1 libxdamage1 libxfixes3 libxrandr2 libgbm1 libcairo2 libpango-1.0-0 libasound2 \
 && rm -rf /var/lib/apt/lists/* \
 && apt-get clean
#RUN apt-get update \
# && apt-get install -y --no-install-recommends chromium \
# && rm -rf /var/lib/apt/lists/* \
# && apt-get clean
# install: libglib2.0-0 libnspr4 libnss3 libatk1.0-0 libatk-bridge2.0-0 libcups2 libxkbcommon0 libxcomposite1 libxdamage1 libxfixes3 libxrandr2 libgbm1 libcairo2 libpango-1.0-0 libasound2

# RUN bunx @puppeteer/browsers install chrome@stable --path $HOME/.cache/puppeteer
# COPY --from=install /temp/prod/node_modules node_modules
# COPY --from=install /temp/prod/package.json package.json
# COPY index.ts index.ts

#RUN apt-get update \
# && apt-get install -y --no-install-recommends wget gnupg ca-certificates \
# && wget -q -O - https://dl.google.com/linux/linux_signing_key.pub | gpg --dearmor -o /usr/share/keyrings/google-linux-signing-keyring.gpg \
# && echo "deb [arch=amd64 signed-by=/usr/share/keyrings/google-linux-signing-keyring.gpg] http://dl.google.com/linux/chrome/deb/ stable main" > /etc/apt/sources.list.d/google-chrome.list \
# && apt-get update \
# && apt-get install -y --no-install-recommends google-chrome-stable \
# && rm -rf /var/lib/apt/lists/* \
# && apt-get clean

COPY . .

RUN bun install --frozen-lockfile --production

# USER bun


#ENV PUPPETEER_EXECUTABLE_PATH=/usr/bin/chromium
#ENV PUPPETEER_SKIP_CHROMIUM_DOWNLOAD=true

# RUN bun x puppeteer browsers install
RUN bunx puppeteer browsers install chrome


# run the app
EXPOSE 4242/tcp

ENTRYPOINT [ "bun", "run", "index.ts" ]
